// FBCODE version (with settings for the platform)
// Source is WdtConfig.h auto generated by CMake from .in file
// You MUST change CMakeLists.txt if you are editing this
// (to change the protocol_version for instance)
#pragma once

#define WDT_VERSION_MAJOR 1
#define WDT_VERSION_MINOR 15
#define WDT_VERSION_BUILD 1507280
// Add -fbcode to version str
#define WDT_VERSION_STR "1.15.1507280-fbcode"
// Tie minor and proto version
#define WDT_PROTOCOL_VERSION WDT_VERSION_MINOR

#define HAS_POSIX_FALLOCATE 1
#define HAS_SYNC_FILE_RANGE 1
